import './CardWidget.css'

const CardWidget = () => {
    const imgCarrito = "https://www.google.com/search?q=imagen+carrito+de+compras&sxsrf=APwXEddRC08ym9zSbPQiBSgDpd7DJ1V8Sw%3A1683156420702&ei=xO1SZPetKqPJ1sQP5cO9qA4&ved=0ahUKEwj3n7qkptr-AhWjpJUCHeVhD-UQ4dUDCBA&uact=5&oq=imagen+carrito+de+compras&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIFCAAQgAQyBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgjEIoFECc6CwgAEIAEELEDEIMBOgsILhCKBRCxAxCDAToLCC4QgAQQsQMQgwE6CAgAEIAEELEDOgoILhCKBRDUAhBDOgoIABCKBRCxAxBDOgcIABCKBRBDOhMILhCKBRCxAxCDARDHARDRAxBDOgsIABCKBRCxAxCDAToYCC4QigUQ1AIQQxCXBRDcBBDeBBDfBBgBOg0IABCKBRCxAxCDARBDOhMILhCDARDHARCxAxDRAxCKBRBDOgoILhCxAxCKBRBDOg0ILhCKBRDHARDRAxBDOgcILhCKBRBDOgoILhCKBRCxAxBDOhUILhCKBRBDEJcFENwEEN4EEOAEGAE6CAguEIAEELEDOhQILhCABBCxAxCDARDHARCvARDUAjoRCC4QigUQsQMQgwEQxwEQrwE6HwguEIoFELEDEIMBEMcBEK8BEJcFENwEEN4EEOAEGAE6CwguEIAEEMcBEK8BOhkILhCABBDHARCvARCXBRDcBBDeBBDgBBgBOgoIABCABBAUEIcCOggIABAWEB4QDzoKCAAQFhAeEA8QCkoECEEYAFAAWM32IWDa9yFoAHABeACAAaIBiAHeGZIBBTE5LjEzmAEAoAEBwAEB2gEGCAEQARgU&sclient=gws-wiz-serp#imgrc=thuo0DDU1EH7XM"
  return (
    <div>
        <img className='imgCarrito' src={imgCarrito} alt='Carrito de compras' />
        <strong> 2 </strong>
        </div>
  )
}

export default CardWidget